apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "minio.fullname" . }}
spec:
  serviceName: {{ include "minio.fullname" . }}
  replicas: {{ .Values.minio.replicas }}
  selector:
    matchLabels:
      app: {{ include "minio.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "minio.name" . }}
    spec:
      containers:
        - name: minio
          image: "{{ .Values.image.repository }}"
          args:
            {{- range .Values.image.args }}
            - {{ . }}
            {{- end }}
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /export
          envFrom:
            - secretRef:
                name: minio-secret
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass }}
