apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "minio.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: {{ index .Values.ingress.hosts 0 }}  # Corrected to use hosts array
      http:
        paths:
        - path: /minio/health/ready
          pathType: Prefix
          backend:
            service:
              name: {{ include "minio.fullname" . }}
              port:
                number: {{ .Values.service.api.port }}

    - host: {{ index .Values.ingress.hosts 1 }}  # Corrected to use hosts array
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "minio.fullname" . }}
              port:
                number: {{ .Values.service.web.port }}

