apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.env.MINIO_ROOT_USER | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.env.MINIO_ROOT_PASSWORD | b64enc | quote }}
