apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    app: {{ include "minio.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "minio.name" . }}
  ports:
    - name: api-port
      port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
    
    - name: web-port
      port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.targetPort }}
  type: {{ .Values.service.type }}
