{{- if .Values.persistence.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistence.storageClassName | default "microk8s-hostpath-immediate" }}  # Simple name without nested fields
provisioner: {{ .Values.persistence.provisioner | default "microk8s.io/hostpath" }}
volumeBindingMode: {{ .Values.persistence.volumeBindingMode | default "Immediate" }}
reclaimPolicy: {{ .Values.persistence.reclaimPolicy | default "Delete" }}
{{- end }}

